---
label: Services
hide_body: true
display_field: serv_title
fields:
- type: text
  name: services_title
  label: Title
- type: textarea
  name: services_paragraph
  label: Paragraph
- name: serviceslist_heading
  type: text
  config:
    required: false
  label: List Heading
pages:
- src/content/services/services.md
