---
label: Services
hide_body: true
fields:
  - type: text
    name: serv_title
    label: Title
  - type: textarea
    name: serv_paragraph
    label: Paragraph
  - name: serv_list_heading
    type: text
    config:
      required: false
    label: List Heading
