---
label: Services
hide_body: true
display_field: services_title
fields:
  - type: text
    name: services_title
    label: Title
  - type: textarea
    name: services_paragraph
    label: Paragraph
    default: ""
    config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  - name: serviceslist_heading
    type: text
    config:
      required: false
    label: List Heading
pages:
  - src/content/services/Services.mdx
